-- ── Txirrindularien izen-formatua ─────────────────────────────────────────────
-- phpMyAdmin-en behin exekutatu (zerbitzariko MySQL-en).
-- Zutabea izen bakoitzaren token-egitura adierazten du: Abizena / Izena hitzez.
-- ALTER-ek errorea emango du zutabea jada badago (kalterik gabe; jarraitu UPDATEekin).
-- Iturria: uneko Txirrindulariak zerrenda (552), 'Izena'z lotuta (UNIQUE giltza).

ALTER TABLE Txirrindulariak ADD COLUMN Izen_Formatua VARCHAR(40) DEFAULT NULL;

UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Abel Balderstone';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Afonso Eulálio';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Aimé De Gendt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alberto Bettiol';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alberto Dainese';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alessandro Covi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Alessandro De Marchi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alessandro Fancellu';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alex Aranburu';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alex Baudin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alex Edmondson';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alex Kirsch';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alex Molenaar';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alexander Krieger';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alexander Kristoff';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alexandre Delettre';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Alexey Lutsenko';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Amanuel Ghebreigzabhier';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Amaury Capiot';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Anders Foldager';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Anders Halland Johannessen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Andrea Bagioli';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Andreas Kron';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Andreas Leknessund';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Angel Madrazo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Anthon Charmig';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Anthony Roux';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'António Morgado';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Arnaud De Lie';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Arnaud Demare';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Arne Marit';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Arvid De Kleijn';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Axel Huens';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Axel Laurance';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Axel Zingle';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Bart Lemmen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Bauke Mollema';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Ben Healy';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Benoit Cosnefroy';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Biniam Girmay';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Bob Jungels';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Brady Gilmore';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Bram Welten';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Brandon Mcnulty';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Brent Van Moer';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Bruno Armirail';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Bryan Coquard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Caleb Ewan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Carl-Frederik Bévort';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Carlos Barbero';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Carlos Canal';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Cees Bol';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Chad Haga';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Chris Froome';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Chris Harper';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Christophe Laporte';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Christopher Hamilton';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Clement Venturini';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Clément Berthet';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Clément Braz Afonso';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Clément Champoussin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Craps Lars';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Daan Hoole';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Damiano Caruso';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Damien Howson';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Daniel Felipe Martínez';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Daniel Martin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Daniel Mclay';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Daryl Impey';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena Abizena' WHERE Izena = 'David De La Cruz';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'David Dekker';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'David Gaudu';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'David González';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Davide Bais';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Davide Ballerini';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Davide Bomboi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Davide Cimolai';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Davide Formolo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Dehairs Simon';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Derek Gee';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Diego Andres Camargo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Dorian Godon';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Dries De Bondt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Dries Devenyns';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Dylan Groenewegen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Dylan Teuns';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Eddie Dunbar';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Edoardo Affini';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Edward Dunbar';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Egan Bernal';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Emanuel Buchmann';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Emilien Jeanniere';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Emmanuel Morin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Enric Mas';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Erlend Blikra';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Esteban Chaves';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Ethan Hayter';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Ewen Costiou';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Fabian Lienhard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Fabio Aru';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Fabio Christen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Fabio Jakobsen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Fausto Masnada';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Felix Engelhardt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Felix Gall';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Felix Grossschartner';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Fernando Barceló';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Fernando Gaviria';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Filippo Baroncini';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Filippo Conca';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Filippo Fiorelli';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Filippo Ganna';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Filippo Magli';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Finn Fisher-Black';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Francesco Busatto';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Francisco Galván';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'François Bidard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Fredrik Dversnes Lavik';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Frits Biesterbos';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Garofoli Gianmarco';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Geoffrey Bouchard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'George Bennett';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Gianni Vermeersch';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Gijs Leemreize';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Gino Mäder';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Giovanni Lonardi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Giulio Ciccone';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Gorka Izagirre';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Guillaume Boivin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Guillaume Martin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Harm Vanhoucke';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Harold Martín López';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Harrison Sweeny';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Hugh Carthy';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Hugo Hofstetter';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Hugo Houle';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Igor Arrieta';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Ion Izagirre';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Isaac Del Toro';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Itamar Einhorn';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Iván García Cortina';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jack Haig';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jacopo Mosca';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jai Hindley';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jakub Mareczko';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jan Bakelants';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jan Christen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jan Hirt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jan Polanc';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jason Tesson';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jaume Guardeño';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jay McCarthy';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Jefferson Alexander Cepeda';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Jefferson Alveiro Cepeda';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jefferson Cepeda';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jenno Berckmoes';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jenthe Biermans';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jesus Herrada';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jhonatan Narváez';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jimmy Janssens';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Johannes Kulset';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'John Degenkolb';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jon Aberasturi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jon Barrenetxea';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jonas Abrahamsen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jonas Geens';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jonas Koch';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jonathan Caicedo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jonathan Castroviejo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Jonathan Lastra Martinez';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jonathan Milan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jordan Jegat';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jordan Labrosse';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jordi Meeus';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Jose Herrada';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Josef Černý';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Joseph Blackmore';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Josh Kench';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'José Joaquín Rojas';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'João Almeida';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Juan Ayuso';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Juan Guillermo Martinez';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Juan Pedro Lopez';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Juan Sebastián Molano';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Julen Amezqueta';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Julian Alaphilippe';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Julien Bernard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Juri Hollmann';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Kaden Groves';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Kamil Malecki';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Kasper Asgreen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Kenny Elissonde';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Kevin Inkelaar';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Kobe Goossens';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Laurens De Plus';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lawson Craddock';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Lecerf Junior';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lennard Kämna';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lenny Martinez';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Leo Hayter';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lewis Askey';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lilian Calmejane';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Lipowitz Florian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Livyns Arjen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lloyd Joseph';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lorenzo Fortunato';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Louis Barré';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Louis Meintjes';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Luca Mozzato';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Luis Angel Mate';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Luka Mezgec';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lukas Nerurkar';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lukasz Owsian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Luke Lamperti';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Lukáš Kubiš';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Léo Bisiaux';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Madis Mihkels';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Mads Würtz Schmidt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Marc Hirschi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Marco Brenner';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Marco Frigo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Marco Haller';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Marius Mayrhofer';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mark Cavendish';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mark Donovan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mark Padun';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Markel Beloki';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Markus Hoelgaard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Martin Marcellusi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matej Mohoric';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mathieu Burgaudeau';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matis Louvel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matteo Fabbro';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matteo Jorgenson';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matteo Malucelli';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matteo Moschetti';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matthew Brennan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matthew Holmes';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mattia Bais';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mattia Cattaneo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Matyáš Kopecký';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Maurice Ballerstedt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Max Kanter';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Merhawi Kudus';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Michael Hepburn';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Michael Matthews';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Michał Kwiatkowski';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Michele Gazzoli';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Miguel Angel Lopez';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mike Teunissen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mikel Bizkarra';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mikel Landa';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mikkel Bjerg';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Mikkel Frølich Honoré';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Milan Fretin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Milan Menten';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Milesi Lorenzo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Mirco Maestri';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Neilands Krists';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Niccolò Bonifazio';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Nico Denz';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Nicola Conci';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Nicolas Dalla Valle';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Izena' WHERE Izena = 'Nielsen Magnus Cort';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Nieve Mikel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Nikias Arndt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Nils Eekhoff';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Nils Politt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Abizena' WHERE Izena = 'Norsgaard Mathias Jørgensen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'O''connor Ben';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Odd Christian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Oier Lazkano';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Olav Kooij';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Oldani Stefano';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Oliveira Ivo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Oliveira Nelson';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Oliveira Rui';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Oliver Naesen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Omar Fraile';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Onley Oscar';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Oomen Sam';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Orluis Aular';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Izena' WHERE Izena = 'Osorio Juan Felipe';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Ourselin Paul';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Pablo Castrillo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pacher Quentin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Page Hugo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Paleni Enzo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Paret-Peintre Aurélien';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Paret-Peintre Valentin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Pascal Ackermann';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Pascal Eenkhoorn';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Patrick Konrad';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Pau Miquel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Paul Lapeira';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Paul Magnier';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Pavel Bittner';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pedersen Casper';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pedersen Mads';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Izena' WHERE Izena = 'Pedersen Rasmus Søjberg';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pedrero Antonio';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pellizzari Giulio';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Pello Bilbao';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Penhoët Paul';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Per Strand Hagenes';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pericas Adrià';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Peters Nans';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Petilli Simone';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Peñalver Manuel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Phil Bauhaus';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Philipsen Jasper';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Piccolo Andrea';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pickrell Riley';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pidcock Thomas';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pidcock Tom';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Pierre Gautherat';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Pierre Latour';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Piet Allegaert';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pietrobon Andrea';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Piganzoli Davide';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pinarello Alessandro';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pinot Thibaut';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pithie Laurence';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Planckaert Edward';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Plapp Luke';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Plowright Jensen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pluimers Rick';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Poels Wouter';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pogačar Tadej';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Poole Max';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Power Rob';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Powless Neilson';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Pozzovivo Domenico';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Prades Eduard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Prodhomme Nicolas';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Quinn Sean';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Quintana Nairo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Quinten Hermans';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Raccagni Noviero Andrea';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Rafał Majka';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Ramon Sinkeldam';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Raúl García Pierna';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Remco Evenepoel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Remi Cavagna';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Remijn Senna';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Renard Alexis';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rex Laurenz';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Riccitello Matthew';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Richard Carapaz';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Rigoberto Urán';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Riley Sheehan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Izena' WHERE Izena = 'Rivera Brandon Smith';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Robert Donaldson';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Robert Gesink';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Robin Froidevaux';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rochas Rémy';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rodriguez Carlos';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rodríguez Cristián';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rodríguez Óscar';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Roger Adrià';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Roglič Primož';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Rohan Dennis';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rolland Brieuc';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Romain Bardet';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Romain Grégoire';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Romeo Iván';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Romo Javier';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rondel Mathys';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Ruben Almeida Guerreiro';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Ruben Fernandez';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rubio Einer';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Rudy Molard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Rui Costa';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Rune Herregodts';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Russo Clément';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Rutsch Jonas';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Ryan Archie';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Ryan Gibbons';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Izena' WHERE Izena = 'Salmon Martin Alexander';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Sam Bennett';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Samuele Battistella';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Sander De Pestel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Sandy Dujardin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Santiago Buitrago';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Scaroni Christian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Schachmann Maximilian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Schmid Mauro';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Schwarzmann Michael';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Sebastian Berwick';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Segaert Alec';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Seixas Paul';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Senechal Florian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Sepp Kuss';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Sepúlveda Eduardo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Sergio Geovani Chumil';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Sergio Henao';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Sergio Higuita';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Shaw James';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Sheffield Magnus';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Sicard Romain';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Izena' WHERE Izena = 'Silva Guillermo Thomas';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Simmons Quinn';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Simon Carr';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Simon Clarke';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Simon Geschke';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Simon Julien';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Simone Consonni';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Simone Gualdi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Sivakov Pavel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Sjoerd Bax';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Skjelmose Mattias';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Skujiņš Toms';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Smith Dion';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Sobrero Matteo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Soler Marc';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Sosa Iván';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Soupe Geoffrey';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Stan Dewulf';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Stanisław Aniołkowski';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Stannard Robert';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Stefan Bissegger';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Stefan Küng';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Steff Cras';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Steffen De Schuyteneer';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Steimle Jannik';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Steinhauser Georg';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Stephen Williams';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Steven Kruijswijk';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Stewart Jake';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Stian Edvardsen-Fredheim';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Storer Michael';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Stork Florian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Strong Corbin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Stuyven Jasper';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Sven Erik Bystrøm';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Swift Ben';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Swift Connor';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Izena' WHERE Izena = 'Sánchez Luis León';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Sánchez Pelayo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Søren Kragh Andersen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Sütterlin Jasha';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Taaramäe Rein';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Tao Geoghegan Hart';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tarling Joshua';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tejada Harold';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tesfatsion Natnael';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena Izena' WHERE Izena = 'Teutenberg Tim Torn';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Theuns Edward';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Thibau Nys';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Thibaud Gruel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Thijssen Gerben';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Thomas Benjamin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Thomas De Gendt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Thomas Gachignard';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Thomas Geraint';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Thymen Arensman';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tiberi Antonio';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena Abizena' WHERE Izena = 'Tibor Del Grosso';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Tiesj Benoot';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tiller Rasmus';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Tim Merlier';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tjøtta Martin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Tobias Bayer';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Tobias Halland Johannessen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Izena Abizena' WHERE Izena = 'Tobias Lund Andresen';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Tobias Müller';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Tom Dumoulin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tonelli Alessandro';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Toon Aerts';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Tord Gudmestad';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Townsend Rory';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tratnik Jan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Trentin Matteo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Træen Torstein';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Tulett Ben';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Turgis Anthony';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Turner Ben';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Txomin Juaristi';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Uijtdebroeks Cian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Ulissi Diego';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Urko Berrade';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vacek Karel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vacek Mathias';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Valentin Madouas';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Valgren Michael';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Valter Attila';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Valverde Alejandro';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Aert Wout';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Baarle Dylan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Belle Loe';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Boven Luca';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Abizena Izena' WHERE Izena = 'Van Den Berg Julius';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Abizena Izena' WHERE Izena = 'Van Den Berg Marijn';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Abizena Izena' WHERE Izena = 'Van Den Bossche Fabio';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Abizena Izena' WHERE Izena = 'Van Den Broek Frank';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Abizena Izena' WHERE Izena = 'Van Der Poel Mathieu';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Dijke Mick';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Dijke Tim';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Eetvelt Lennert';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Garderen Tejay';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Gestel Dries';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Gils Maxim';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Poppel Boy';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Poppel Danny';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Rensburg Reinardt';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Uden Casper';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Van Wilder Ilan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vansevenant Mauri';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vauquelin Kévin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Velasco Simone';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vendrame Andrea';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vercher Mattéo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vermaerke Kevin';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vermeersch Florian';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vernon Ethan';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Verona Carlos';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Verre Alessandro';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Verstrynge Emiel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Victor Campenaerts';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Victor Lafay';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Villa Giacomo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Vincenzo Albanese';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Vincenzo Nibali';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vine Jay';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vingegaard Jonas';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Vito Braet';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Viviani Elia';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Vlasov Aleksandr';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Walscheid Max';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Wandahl Frederik';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Warren Barguil';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Watson Samuel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Wellens Tim';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Welsford Sam';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Wilco Kelderman';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'William Barta';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Abizena Izena' WHERE Izena = 'Withen Philipsen Albert';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Woods Michael';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Wright Fred';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Wærenskjold Søren';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Xandro Meurisse';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Yates Adam';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Yates Simon';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Yevgeniy Fedorov';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Yves Lampaert';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Zambanini Edoardo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Zana Filippo';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Zijlaard Maikel';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Zimmermann Georg';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Élie Gesbert';
UPDATE Txirrindulariak SET Izen_Formatua = 'Abizena Izena' WHERE Izena = 'Štybar Zdenek';
UPDATE Txirrindulariak SET Izen_Formatua = 'Izena Abizena' WHERE Izena = 'Žak Eržen';

